### PR TITLE
Lua tracker cleanup

### PR DESCRIPTION
**Pull request by saerdnaer**
TODO: describe what this PR does and how it was tested

### CODE REVIEW

**Comment by takluyver** [comment]
This certainly looks like a big improvement - have we actually tested it on one of the trackers? I'd be reluctant to merge it without some testing, because it won't be obvious to whoever runs the trackers next that the script has been overhauled from a known-working state.

**Comment by saerdnaer** [comment]
I tested it on tracker 1, saw the problems described in #39 and then validated that the old version also has the same bug.

**Comment by takluyver** [comment]
Aha, thanks. But you checked that it was both sending data to the server and recording it on the SD card, with no obvious regressions from the script we used during the competition?

**Comment by saerdnaer** [comment]
I did not check the SD card, AFAIK I saw data on the map. I tried to validate on http://tracking.roboticsailing.org/coordinates but it looks like this view is somehow broken and lists only coordinates from yesterday. But I would suggest that we also switch to comma seperated values for the REST API, like we discussed in #42 for the sd card.

**Comment by takluyver** [comment]
OK, could someone with a tracker device try running it with @saerdnaer's script from this PR, and check that coordinates are written to the SD card? If this is done while the server is still running, it would be great if we could also double check that the server accepts the coordinates that it is sending. I've made some changes on the server side recently.

I agree that it would be good to change to a clearer format for sending data to the server, but let's focus on getting this PR checked and merged. This looks much clearer already, and at some point we're all going to be busy with other things and work on this is likely to stall.

**Comment by tsaoyu** [comment]
I have tested the script on the tracker for:
- [x] SD card data record
- [x] Data transfer via GSM

**Comment by takluyver** [comment]
:+1: thanks @tsaoyu !

**Comment by tsaoyu** [comment]
CSV support on the way 🔨

**Pull request merged**
