### PR TITLE
Latest coordinates endpoint

### PR DESCRIPTION
**Pull request by kirs**
As discussed in https://github.com/WRSC/tracking/issues/3#issuecomment-385264413

Example of the response:

```json
[
  {
    "id": 1071896132,
    "tracker_id": 824207793,
    "datetime": "20180501104904",
    "latitude": "2",
    "longitude": "1",
    "robot_id": 995256502,
    "robot_name": "snowball",
    "team_id": 990681772,
    "team_name": "senators"
  },
  {
    "id": 1071896133,
    "tracker_id": 409766844,
    "datetime": "20180501104904",
    "latitude": "2",
    "longitude": "1",
    "robot_id": 1046216088,
    "robot_name": "testotron",
    "team_id": 695669099,
    "team_name": "SylvainTeam"
  }
]
```

### CODE REVIEW

**Comment by kirs** [comment]
@takluyver does this look like something you imagined?

**Comment by takluyver** [comment]
Yup, that looks promising. cc @smaria 

What URL path would that be accessible at? Or does it need another change to add URL routing?

Does the `id` field for each boat remain the same as the coordinates update, or does it get a new ID each time? Either is probably OK, but it will be important to document things like this carefully. I might also be tempted to drop a few of the various id fields, to avoid confusion.

**Comment by kirs** [comment]
It will be available at `/missions/{mission_id}/coordinates`. I'm also open to change the last part to `current_coordinates` or `latest_coordinates`.

The top-level `id` key is the coordinate ID. So it would change as new coordinates are inserted. It's probably for the best to remove that one to avoid confusion.

**Comment by takluyver** [comment]
I think I'd go for `latest_coordinates` - if there are interruptions in the data, then they may not be *current*.

Yes, let's get rid of `id` unless we think of a reason for it. I'd also get rid of `team_id`, because it will likely be redundant with the boat id. Keeping boat_id and tracker_id seems potentially reasonable - a boat may make more than one attempt with different trackers.

Is it possible to put the timestamps in ISO 8601 format? E.g. `2018-05-01T12:32:13.123Z` .

**Comment by kirs** [comment]
Are you OK with `robot_id` not `boat_id`? I agree that `boat` makes more sense, but `Robot` is the term used across the code base and it would be nice to keep it consistent. Unless we decide to globally name "robots" to "boats".

> Is it possible to put the timestamps in ISO 8601 format?

Sure. For some reason we store the `datetime` column of coordinates as a string: https://github.com/WRSC/tracking/blob/196843ba532fe88f42f12f0c0184d390529dafbb/MYR_rails/db/schema.rb#L36

**Comment by takluyver** [comment]
My mistake - robot_id is fine, and we should definitely be consistent across the codebase.

> For some reason we store the datetime column of coordinates as a string: 

Hmm. I guess we could probably change that, but that's something where I'd definitely want to have plenty of tests first, including tests for bad input. So for now, let's just reformat it from the stored string to the ISO format in the handler.

(I won't hold the PR up for this, but @smaria it just occurred to me: is a single coordinate per boat enough, or do we want to provide e.g. the last 50 points for each boat, so you can try to work out where they're going?)

**Comment by kirs** [comment]
> (I won't hold the PR up for this, but @smaria it just occurred to me: is a single coordinate per boat enough, or do we want to provide e.g. the last 50 points for each boat, so you can try to work out where they're going?)

Hmm, that sounds useful. At the same time (I guess) the most common use case would be to fetch single latest coordinates.

What about `?limit=50` as a URL parameter that would allow you to get more coordinates per boat/tracker? The default would still be a single coordinate.

**Comment by takluyver** [comment]
That might make sense, with a suitable maximum limit so people can't ask for 5 million points. But let's wait for Sophia's input on what we want from the competition POV.

**Comment by smaria** [comment]
what are 'active boats'? Is this based on registered trackers, or on a timeout?
I think being able to request a backlog may be very useful. Teams would probably filter this based on location and/or time, but they should have all info needed to do that themselves.

Looking at the information included, I think there are really two paths: 

- All information may be useful, in which case I would actually keep the 'id' field as well - I could imagine it could come in handy to remove duplicates, e.g. if a boat is not transmitting any new data, or when working with a backlog. I would maybe rename it a bit clearer - log_entry_id?

- keep it simple, in which case I would reduce it to key information: datetime, latitude, longitude, robot_name

Teams relaying this information to their boat would probably prefer the simple format, since data amount may still be an issue for some methods. On the other hand they can easily drop unused data before re-transmission, so overall I think a more extensive set of information sounds better to me at the moment.

**Comment by takluyver** [comment]
Great, so I think the URL parameter (`?limit=50`) idea sounds good, then teams can decide how much they want. Maximum of 1000 points per boat, perhaps? The current proposed format is about 300 bytes per point, so 300 * 1000 points * 10 boats would be 3 MB. But we can probably make it slgithly more efficient for this model:

```json
[
  {
    "boat_id": 3,
    "other_boat_info": "...",
    "points": [
      {
        "latitude": 52.4,
        "longitude": -1.3,
        "timestamp": "2018-05-01T22:13:43.445Z"
      }
    ]
  }
]
```

**Comment by smaria** [comment]
So you would get rid of the log_entry_id, and group robot_name, team_name, team_id, and tracker_id in the other_robot_info?

I don't really see a purpose for including a lot of other_robot_info, except maybe for team_name - in case a team wants to react to a specific other team, they then don't have to figure out the ID themselves.

One concern I have with the new suggested structure: Are there use cases for keeping a log_entry_id, or does the timestamp server as a sufficient ID? Switching to the structure just proposed by @takluyver would not allow us to include it again.

**Comment by takluyver** [comment]
Sorry, I was being lazy - I don't think we should have a field actually called `other_robot_info`, I just meant that as a placeholder for whatever other fields would go at that level. And I accidentally called it `boat_id` again instead of `robot_id`.

I'm also fine with each coordinate having some ID. I only meant to illustrate the idea of having boat level info once rather than repeated in each coordinate.

**Comment by smaria** [comment]
Ah now I get it, we can still add an ID, should we find the timestamp doesn't work. I'd probably keep it simple for now, and use the timestamp as an ID. Removing the repeats sounds logical to me. Maybe 'positions' or 'recorded_positions' is a bit clearer as a name for points?

**Comment by takluyver** [comment]
Good point, that avoids confusion with other kinds of point !

**Comment by kirs** [comment]
Thanks for feedback! I updated the code. Here's the result JSON:

```json
[
  {
    "tracker_id": 824207793,
    "robot_id": 995256502,
    "robot_name": "snowball",
    "team_name": "senators",
    "latest_coordinates": [
      {
        "id": 1071896132,
        "latitude": "2",
        "longitude": "1",
        "datetime": "2018-05-05T21:01:55Z"
      }
    ]
  },
  {
    "tracker_id": 409766844,
    "robot_id": 1046216088,
    "robot_name": "testotron",
    "team_name": "SylvainTeam",
    "latest_coordinates": [
      {
        "id": 1071896133,
        "latitude": "2",
        "longitude": "1",
        "datetime": "2018-05-05T21:01:55Z"
      }
    ]
  }
]
```

(`?limit=50` parameter also takes into account. Max value is 500).

**Comment by kirs** [comment]
I decided to keep `id` of coordinate to avoid confusion in case someone submits the more than one coordinate with the same `datetime`.

**Comment by takluyver** [comment]
Thanks, that looks good.

**Pull request merged**
